# Generated by Django 2.2 on 2020-01-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200122_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
