# Generated by Django 2.2 on 2020-01-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200122_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='last_users',
            old_name='IP',
            new_name='ip',
        ),
    ]
