# Generated by Django 2.2 on 2020-01-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200123_2223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Last_Users',
            new_name='Last_User',
        ),
    ]
