# Generated by Django 2.2 on 2020-01-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200123_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last_user',
            name='ip',
            field=models.CharField(max_length=32),
        ),
    ]
